version: '3.8'

services:
  php:
    build:
      context: ./php
    volumes:
      - ../symfony:/var/www/symfony
    networks:
      - symfony_network
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=symfony
      - DATABASE_USER=symfony
      - DATABASE_PASSWORD=secret

  caddy:
    image: caddy:2
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ../nextjs:/usr/share/caddy/nextjs
      - ../symfony:/usr/share/caddy/symfony
    ports:
      - "80:80"
    networks:
      - symfony_network

  nextjs:
    build:
      context: ./nextjs
    volumes:
      - ../nextjs:/app
    ports:
      - "3000:3000"
    networks:
      - symfony_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: symfony
      PMA_PASSWORD: secret
    networks:
      - symfony_network

networks:
  symfony_network:

volumes:
  caddy_data:
  caddy_config:
  db_data:
